[package]
name = "Ejercicio-1"
version = "0.1.0"
edition = "2021"
authors = ["Rafael Rodriguez <rafael.rodriguez@correo.ucu.edu.uy>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
