task :default => [:run]

task :run do
  sh "rake compile && ruby lib/rubyinterpreter.rb"
end

task :compile do
  sh "rake clean && cd lib && racc parser.racc -o parser.rb && cd .."
end

task :clean do
  sh "cd lib && del parser.rb && cd .."
end

task :test do
  Dir.glob("specs/*Test.rb").each do |file|
    sh "ruby #{file}"
  end
end