[package]
name = "ejercicio-2_2"
version = "0.2.2"
edition = "2021"
authors = ["Rafael Rodriguez <rafael.rodriguez@correo.ucu.edu.uy>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "1.4"
